# Generated by Django 6.0.5 on 2026-07-01 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_month', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('city', models.CharField(choices=[('Addis Ababa', 'Addis Ababa (General/Central)'), ('Bole', 'Bole, Addis Ababa'), ('CMC', 'CMC, Addis Ababa'), ('Kazanchis', 'Kazanchis, Addis Ababa'), ('Old Airport', 'Old Airport, Addis Ababa'), ('Mexico', 'Mexico, Addis Ababa'), ('Ayat', 'Ayat, Addis Ababa'), ('Summit', 'Summit, Addis Ababa'), ('Lideta', 'Lideta, Addis Ababa'), ('Sarbet', 'Sarbet, Addis Ababa')], default='Addis Ababa', max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('kitchen', models.PositiveIntegerField(default=1)),
                ('living_room', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Villa', 'Villa'), ('Studio', 'Studio')], default='Apartment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('booked', 'Booked'), ('hidden', 'Hidden by Admin'), ('sold', 'Sold')], default='pending', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('featured_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('room_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
    ]
