# Generated by Django 6.0.5 on 2026-07-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price_per_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='listingimage',
            name='room_type',
            field=models.CharField(choices=[('overall', 'Overall property photos'), ('kitchen', 'Kitchen'), ('living_room', 'Living room'), ('bedroom', 'Bedroom'), ('bathroom', 'Bathroom')], default='overall', max_length=50),
        ),
    ]
